import {
  AttachedWashroomIcon,
  BedIcon,
  BreakfastIcon,
  CctvIcon,
  DinnerIcon,
  GymIcon,
  HighTeaIcon,
  HotWaterIcon,
  InductionIcon,
  LiftIcon,
  LunchIcon,
  MatrisIcon,
  NonVegIcon,
  ParkingIcon,
  RefrigratorIcon,
  SelfCookingIcon,
  TableIcon,
  TvIcon,
  VegIcon,
  WardrobeIcon,
  WashingMachineIcon,
  WifiIcon,
} from "@/assets/icons";
import AllTypeFoodIcon from "@/assets/icons/AllTypeFoodIcon";
import ChairIcon from "@/assets/icons/ChairIcon";
import LaundryIcon from "@/assets/icons/LaundryIcon";
import WaterPurifierIcon from "@/assets/icons/WaterPurifierIcon";

export const facilitiesIconList = {
  Breakfast: <BreakfastIcon />,
  Lunch: <LunchIcon />,
  "High Tea": <HighTeaIcon />,
  Dinner: <DinnerIcon />,
  Vegitarian: <VegIcon />,
  "Non-Vegitarian": <NonVegIcon />,
  All: <AllTypeFoodIcon />,
  "Attached Bathroom": <AttachedWashroomIcon />,
  Chair: <ChairIcon />,
  "Study Table": <TableIcon />,
  Mattress: <MatrisIcon />,
  Wardrobe: <WardrobeIcon />,
  "Water Purifier": <WaterPurifierIcon />,
  Wifi: <WifiIcon />,
  Refrigerator: <RefrigratorIcon />,
  CCTV: <CctvIcon />,
  "Hot water": <HotWaterIcon />,
  "Self Cooking": <SelfCookingIcon />,
  Induction: <InductionIcon />,
  Laundry: <LaundryIcon />,
  "Washing Machine": <WashingMachineIcon />,
  Parking: <ParkingIcon />,
  Lift: <LiftIcon />,
  Gym: <GymIcon />,
  Tv: <TvIcon />,
  Bed: <BedIcon />,
};
